RazorPages/Entities/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPages.Entities
{
    public class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Score { get; set; }
    }
}

RazorPages/Models/StudentListViewModel.cs
using RazorPages.Entities;
using System.Collections.Generic;

namespace RazorPages.Models
{
    public class StudentListViewModel
    {
        public List<Student> Students { get; set; }
    }
}

RazorPages/Controllers/CommonController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPages.Controllers
{
    public class CommonController : Controller
    {
        [Route("/error")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

RazorPages/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RazorPages.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Threading.Tasks;

namespace RazorPages.Controllers
{

    public class HomeController : Controller
    {
        public HomeController()
        {
            int a = 10;
        }
        [HandleException(ViewName = "DivideByZeroException", ExceptionType =typeof(DivideByZeroException))]
        [HandleException(ViewName = "Error", ExceptionType =typeof(SecurityException))]
        public IActionResult Index()
        {
            //throw new SecurityException("Some exception");

            return View();
        }
        
        public IActionResult Index2()
        {
           // throw new Exception("Some exception");
            return View();
        }
    }
}

RazorPages/Pages/Customer/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPages.Pages.Customer
{
    public class IndexModel : PageModel
    {
        public string Message { get; set; }
        public void OnGet()
        {
            Message += "Our element rendered";
            Message += " at this time" + DateTime.Now;
        }
    }
}

RazorPages/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPages.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

RazorPages/Pages/StudentPage/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPages.DATA;
using RazorPages.Entities;

namespace RazorPages.Pages.StudentPage
{
    public class IndexModel : PageModel
    {
        private readonly StudentDbContext _context;

        public IndexModel(StudentDbContext context)
        {
            _context = context;
        }
        public List<Student> Students { get; set; }
        public void OnGet(string s=null)
        {
            Students = string.IsNullOrEmpty(Search)
                ?_context.Students.ToList()
                : _context.Students.Where(st=>st.Name.Contains(Search)).ToList();
            Student1 = Students[0];
        }
        [BindProperty(SupportsGet =true)]
        public string Search { get; set; }
        public Student Student1 { get; set; }

        [BindProperty]
        public Student Student { get; set; }
        public IActionResult OnPost()
        {
            _context.Students.Add(Student);
            _context.SaveChanges();
            return RedirectToPage("/StudentPage/Index");
        }



    }
}

RazorPages/ViewComponents/StudentListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using RazorPages.DATA;
using RazorPages.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPages.ViewComponents
{
    public class StudentListViewComponent:ViewComponent
    {
        private readonly StudentDbContext _context;

        public StudentListViewComponent(StudentDbContext context)
        {
            _context = context;
        }
        public ViewViewComponentResult Invoke(string filter)
        {
            filter = HttpContext.Request.Query["filter"];
            return View(new StudentListViewModel
            {
                Students=_context.Students.Where(s=>s.Name.Contains(filter)).ToList()
            });
        }
    }
}

RazorPages/Pages/Customer/Index.cshtml
@page
@model RazorPages.Pages.Customer.IndexModel
@{

}

<!DOCTYPE html>

<html>

<head>

</head>
<body>

    <h1>Customer Pages</h1>
    <h2>@DateTime.Now</h2>
    <h1>@Model.Message</h1>
</body>
</html>

RazorPages/Pages/Index.cshtml
@page
@model RazorPages.Pages.IndexModel
@{
}

<!DOCTYPE html>

<html>

<head>

</head>
<body>

    <h1>HOME Pages</h1>
    <h2>@DateTime.Now</h2>

</body>
</html>

RazorPages/Pages/StudentPage/Index.cshtml
@page
@model RazorPages.Pages.StudentPage.IndexModel
@{
}
<!DOCTYPE html>

<html>

<head>
   <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>

    <h1>Student Page</h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Score</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var s in Model.Students){
            <tr>
                <th scope="row">@s.Id</th>
                <td>@s.Name</td>
                <td>@s.Score</td>
                <td>
                    <a asp-page-handler="" class="btn btn-danger" >Edit</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
    <form method="get">
        Search : <input asp-for="Search" />

        <input type="submit" value="Submit" />
    </form>
    <form method="post">
        Name : <input asp-for="Student.Name" />
        Score : <input asp-for="Student.Score" />
        <input type="submit" value="Submit" />
    </form>
    <form method="get">
        Name : <input asp-for="Student1.Name" />
        Score : <input asp-for="Student1.Score" />
        <input type="submit" value="Submit" />
    </form>
</body>
</html>

RazorPages/Views/Common/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div style="padding:5px;background-color:red;">
    <h1>Error</h1>
    <p>Some Error Ocurred</p>
</div>

RazorPages/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}


<div>

     <h1>HOME</h1>

</div>

RazorPages/Views/Shared/Components/StudentList/Default.cshtml
@model RazorPages.Models.StudentListViewModel

@foreach (var student in Model.Students)
{
    @student.Id
    @student.Name
    <hr>
}

RazorPages/Views/Shared/DivideByZeroException.cshtml
@{
    Exception ex = ViewData["HandleException"] as Exception;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DivideByZeroException</title>
</head>
<body>
    <h1>DivideByZeroException</h1>
    <p>@ex.Message</p>
</body>
</html>

RazorPages/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @await Component.InvokeAsync("StudentList",new {filter=""})
    </div>
    <div>
        @RenderBody()
    </div>
</body>
</html>